# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - aisightapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Upgrade pip
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Install Playwright browsers (if needed)
        run: |
          source venv/bin/activate
          if pip list | grep -q playwright; then
            echo "Playwright detected, installing browsers..."
            playwright install --with-deps chromium
          else
            echo "Playwright not in requirements.txt, skipping browser installation"
          fi

      - name: Verify critical packages
        run: |
          source venv/bin/activate
          python -c "import fastapi; print(f'FastAPI: {fastapi.__version__}')"
          python -c "import pydantic; print(f'Pydantic: {pydantic.__version__}')"
          python -c "import uvicorn; print(f'Uvicorn: {uvicorn.__version__}')"
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B2F86267839A45688A782CDC2FFBD7D9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5AF63C37122943E784A3A32CC1DD78E4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E57F42B91EA04438A3B0CB10F3317C4B }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'aisightapi'
          slot-name: 'Production'
          